# Generated by Django 5.1 on 2024-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('ast', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=100)),
                ('department', models.CharField(max_length=155)),
                ('salary', models.FloatField()),
                ('experience', models.ImageField(upload_to='')),
            ],
        ),
    ]
